name: json-tui
adopt-info: json-tui
summary: A json visualizer with a terminal UI.
description: A json visualizer with a terminal UI.

grade: stable
confinement: strict
base: core18

apps:
  json-tui:
    command: json-tui
    plugs:
      - home

parts:
  json-tui:
    plugin: cmake
    source: https://github.com/ArthurSonzogni/json-tui
    source-type: git
    build-snaps: [cmake/latest/edge] # We need a modern cmake.
    stage-packages:
      - git
    override-build: |
      /snap/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL\
        -DCMAKE_BUILD_TYPE=Release \
        $SNAPCRAFT_PART_SRC
      make -j 4
      make install
      GIT_TUI_VERSION=`$SNAPCRAFT_PART_INSTALL/bin/json-tui version`;
      snapcraftctl set-version "${GIT_TUI_VERSION}"

passthrough:
  title: json-tui
  license: MIT
